services:
  - type: web
    name: fastapi-backend
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=8000
    plan: free
    branch: main  # pas dit aan als je branch anders heet
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8000
